server:
  port: 9999

spring:
  application:
    name: demo-springcloud-z
  cloud:
    nacos:
      discovery:
        server-addr: 10.10.8.167:8848
        metadata:
          group-name: demo
          version: 0.0.1-SNAPSHOT
