spring:
  application:
    name: demo-springcloud-nacos
  cloud:
    nacos:
      discovery:
        server-addr: 10.10.8.167:8848
        metadata:
          groupName: demo
          version: 0.0.1-SNAPSHOT
