server:
  port: 7777

spring:
  application:
    name: demo-springcloud-y
  cloud:
    nacos:
      discovery:
        server-addr: 10.10.8.167:8848
        metadata:
          group-name: demo
          version: 0.0.1-SNAPSHOT
  zipkin:
    base-url: http://10.10.8.167:9411
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.8.167:3306/gitlab?statementInterceptors=brave.mysql.TracingStatementInterceptor&zipkinServiceName=demo-springboot-y&useSSL=false
    username: root
    password: 123456