server:
  port: 7777

spring:
  application:
    name: demo-springcloud-y
  cloud:
    nacos:
      discovery:
        server-addr: mse-4e2a3680-nacos-ans.mse.aliyuncs.com:8848
        metadata:
          group-name: demo
          version: 0.0.1-SNAPSHOT
