spring:
  application:
    name: demo-springcloud-openfeign
  cloud:
    nacos:
      discovery:
        server-addr: 10.10.8.167:8848
        metadata:
          group-name: demo
          version: 0.0.1-SNAPSHOT
